# Вариант 5

In [101]:
from random import randint
import numpy as np

class FibNumberGenerator:
    mod = 0xFFFFFFF
    numbers = [0, 1, 1]

    def get_number(self, i: int):
        
        while len(self.numbers) <= i:
            index = len(self.numbers)

            self.numbers.append(self.numbers[index - 1] + self.numbers[index - 2])

        return self.numbers[i] % self.mod

gen = FibNumberGenerator()

## Задание 1

In [102]:
size = (512, 128)
generation_range = (-8, 8)

matrix = np.matrix([[randint(a=generation_range[0], b=generation_range[1]) for _ in range(size[1])] for _ in range(size[0])])

print(*matrix, sep='\n')

[[-1  2 -8 -8 -5  8  5 -4  8  5  4 -6 -5  3 -7  0 -2  5 -4 -7  0  6  7  7
  -4 -3  4  2  3  3  5  4  2  6 -2 -5 -8 -7  6 -6  5  2 -3  0 -4  1  1  7
  -5  0  8  0  6 -5  6 -6 -1 -2  6  4 -5 -6  4  8  7 -6  5 -8 -8  6  0 -2
  -2 -2  3 -8 -2 -3 -5  3  5  5  0  1  0 -1  4  7  5  4  6 -4 -2  2  5 -8
  -7  2  2  3  5  6  1 -3 -1 -8 -6 -1  3  0 -6  3 -5  7  4  3  1  4 -7 -3
   4 -8  2 -3 -8  8 -3 -1]]
[[ 5 -4 -6  6  6  6 -7 -7  5  5 -5  6  6 -4  0  3 -7 -2  6  8 -7  5  2 -7
   4 -3  2  4 -1 -3 -8 -3  8 -8 -7 -3  3  1  0 -5 -8  0 -6  5  5 -6 -5 -3
  -7  4  5 -6  4 -4 -5 -4 -5 -1  0  8  1  7 -5  6  6 -5 -2 -6 -1  7  6  7
   2  7  6 -1 -1  7 -6  6  1  8  8  1 -2  1  2  4  2  1 -2 -5  3  8  6 -5
   6  8 -6 -6  1 -4  0  8 -8 -1 -1 -1  2 -8  3  1  0  4 -7  4  1 -4  1 -5
  -2  5 -3 -4  2 -1  2  3]]
[[ 3 -3 -1 -1  7  0  0  5 -8 -6  8  1 -2  7 -1 -6  5 -5 -5 -4 -5 -1  6  6
   1  3  2 -7 -2 -6 -6  2  3  2  6  1  6  6  3 -6 -3  2 -3 -5 -7  3 -4 -7
  -8  1 -2 -3 -6 -1  4  0  7 -5  0  1 -7 -8 -7  8  0  3 

## Задание 2

In [103]:
size = 128
first = 0
step = 3

replace = 128

vector = first + np.arange(0, size) * step

matrix[replace] = vector

print('vector')
print(vector)
print('matrix')
print(*matrix, sep='\n')

vector
[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213
 216 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267
 270 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321
 324 327 330 333 336 339 342 345 348 351 354 357 360 363 366 369 372 375
 378 381]
matrix
[[-1  2 -8 -8 -5  8  5 -4  8  5  4 -6 -5  3 -7  0 -2  5 -4 -7  0  6  7  7
  -4 -3  4  2  3  3  5  4  2  6 -2 -5 -8 -7  6 -6  5  2 -3  0 -4  1  1  7
  -5  0  8  0  6 -5  6 -6 -1 -2  6  4 -5 -6  4  8  7 -6  5 -8 -8  6  0 -2
  -2 -2  3 -8 -2 -3 -5  3  5  5  0  1  0 -1  4  7  5  4  6 -4 -2  2  5 -8
  -7  2  2  3  5  6  1 -3 -1 -8 -6 -1  3  0 -6  3 -5  7  4  3  1  4 -7 -3
   4 -8  2 -3 -8  8 -3 -1]]
[[ 5 -4 -6  6  6  6 -7 -7  5  5 -5  6  6 -4  0  3 -7 -2  6  8 -7  5

## Задание 3

In [107]:
size = 512
replace = 100

column = [gen.get_number(i + 1) for i in np.arange(0, size)]

matrix[:, replace] = np.array([np.array([x], dtype=str) for x in column])

print('vector')
print(column)
print('matrix')
print(*matrix, sep='\n')

vector
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 165058982, 164537823, 61161350, 225699173, 18425068, 244124241, 262549309, 238238095, 232351949, 202154589, 166071083, 99790217, 265861300, 97216062, 94641907, 191857969, 18064421, 209922390, 227986811, 169473746, 129025102, 30063393, 159088495, 189151888, 79804928, 521361, 80326289, 80847650, 161173939, 242021589, 134760073, 108346207, 243106280, 83017032, 57687857, 140704889, 198392746, 70662180, 619471, 71281651, 71901122, 143182773, 215083895, 89831213, 36479653, 126310866, 162790519, 20665930, 183456449, 204122379, 119143373, 54830297, 173973670, 228803967, 134342182, 94710694, 229052876, 55328115, 15945536, 71273651, 87219187, 158492838, 245712025, 135769408, 113045978, 248815386, 93425909, 738058

## Задание 4

In [105]:
sub_size = (20, 20)
point_a = (0, 0)
point_b = (100, 100)

matrix_a = matrix[point_a[0]:point_a[0]+sub_size[0], point_a[1]:point_a[1] + sub_size[1]]
matrix_b = matrix[point_b[0]:point_b[0]+sub_size[0], point_b[1]:point_b[1] + sub_size[1]]

show_size = (16, 4)
show_point = (0, 0)

result = np.matmul(matrix_a, matrix_b)

print(result[show_point[0]:show_point[0]+show_size[0], show_point[1]:show_point[1] + show_size[1]], sep='\n')

[[-1360371786          63          16         110]
 [ -251779025          51         -11         -81]
 [  197071235          -2          31        -155]
 [   16167308        -142         202          70]
 [ 1002449399          90         -57        -119]
 [ -829466575         -50         -47          14]
 [ -985093348         -95         -58         -50]
 [  954832612        -185         153          86]
 [-1730751876         -67        -100        -228]
 [-1013420268         -15          36           1]
 [  378231888        -169         -42          -6]
 [ 1678537012          41         125         106]
 [-1812891925          -3         110          94]
 [ 1819824393        -134          40         -81]
 [   -1315460          43          61        -158]
 [-1937768302          62           9          72]]
